// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/chat_service.proto

package chat

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_v1_chat_service_proto protoreflect.FileDescriptor

const file_v1_chat_service_proto_rawDesc = "" +
	"\n" +
	"\x15v1/chat_service.proto\x12.ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1\x1a\x16v1/chat_messages.proto\x1a\x1cgoogle/api/annotations.proto2\x95\t\n" +
	"\vChatService\x12\xa7\x01\n" +
	"\x10CreateDirectChat\x12G.ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.CreateDirectChatRequest\x1aH.ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.CreateDirectChatResponse\"\x00\x12\x8c\x01\n" +
	"\aGetChat\x12>.ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.GetChatRequest\x1a?.ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.GetChatResponse\"\x00\x12\x9e\x01\n" +
	"\rListUserChats\x12D.ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ListUserChatsRequest\x1aE.ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ListUserChatsResponse\"\x00\x12\xa4\x01\n" +
	"\x0fListChatMembers\x12F.ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ListChatMembersRequest\x1aG.ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ListChatMembersResponse\"\x00\x12\xc2\x01\n" +
	"\vSendMessage\x12B.ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.SendMessageRequest\x1aC.ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.SendMessageResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/chats/{chat_id}/message\x12\x9b\x01\n" +
	"\fListMessages\x12C.ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ListMessagesRequest\x1aD.ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ListMessagesResponse\"\x00\x12\xa1\x01\n" +
	"\x0eStreamMessages\x12E.ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.StreamMessagesRequest\x1aF.ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.StreamMessagesResponse\"\x00B\xc1\x02\n" +
	"2com.ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1B\x10ChatServiceProtoP\x01Z\"msa_big_tech/pkg/api/proto/v1;chat\xa2\x02\x05GCDMC\xaa\x02,Ggithub.Com.DeNisBuLgAkOv.MsaBigTech.Chat.V1\xca\x02,Ggithub\\Com\\DeNisBuLgAkOv\\MsaBigTech\\Chat\\V1\xe2\x028Ggithub\\Com\\DeNisBuLgAkOv\\MsaBigTech\\Chat\\V1\\GPBMetadata\xea\x021Ggithub::Com::DeNisBuLgAkOv::MsaBigTech::Chat::V1b\x06proto3"

var file_v1_chat_service_proto_goTypes = []any{
	(*CreateDirectChatRequest)(nil),  // 0: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.CreateDirectChatRequest
	(*GetChatRequest)(nil),           // 1: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.GetChatRequest
	(*ListUserChatsRequest)(nil),     // 2: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ListUserChatsRequest
	(*ListChatMembersRequest)(nil),   // 3: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ListChatMembersRequest
	(*SendMessageRequest)(nil),       // 4: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.SendMessageRequest
	(*ListMessagesRequest)(nil),      // 5: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ListMessagesRequest
	(*StreamMessagesRequest)(nil),    // 6: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.StreamMessagesRequest
	(*CreateDirectChatResponse)(nil), // 7: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.CreateDirectChatResponse
	(*GetChatResponse)(nil),          // 8: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.GetChatResponse
	(*ListUserChatsResponse)(nil),    // 9: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ListUserChatsResponse
	(*ListChatMembersResponse)(nil),  // 10: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ListChatMembersResponse
	(*SendMessageResponse)(nil),      // 11: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.SendMessageResponse
	(*ListMessagesResponse)(nil),     // 12: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ListMessagesResponse
	(*StreamMessagesResponse)(nil),   // 13: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.StreamMessagesResponse
}
var file_v1_chat_service_proto_depIdxs = []int32{
	0,  // 0: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ChatService.CreateDirectChat:input_type -> ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.CreateDirectChatRequest
	1,  // 1: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ChatService.GetChat:input_type -> ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.GetChatRequest
	2,  // 2: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ChatService.ListUserChats:input_type -> ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ListUserChatsRequest
	3,  // 3: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ChatService.ListChatMembers:input_type -> ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ListChatMembersRequest
	4,  // 4: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ChatService.SendMessage:input_type -> ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.SendMessageRequest
	5,  // 5: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ChatService.ListMessages:input_type -> ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ListMessagesRequest
	6,  // 6: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ChatService.StreamMessages:input_type -> ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.StreamMessagesRequest
	7,  // 7: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ChatService.CreateDirectChat:output_type -> ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.CreateDirectChatResponse
	8,  // 8: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ChatService.GetChat:output_type -> ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.GetChatResponse
	9,  // 9: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ChatService.ListUserChats:output_type -> ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ListUserChatsResponse
	10, // 10: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ChatService.ListChatMembers:output_type -> ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ListChatMembersResponse
	11, // 11: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ChatService.SendMessage:output_type -> ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.SendMessageResponse
	12, // 12: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ChatService.ListMessages:output_type -> ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ListMessagesResponse
	13, // 13: ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.ChatService.StreamMessages:output_type -> ggithub.com.DeNisBuLgAkOv.msa_big_tech.chat.v1.StreamMessagesResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_v1_chat_service_proto_init() }
func file_v1_chat_service_proto_init() {
	if File_v1_chat_service_proto != nil {
		return
	}
	file_v1_chat_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_chat_service_proto_rawDesc), len(file_v1_chat_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_chat_service_proto_goTypes,
		DependencyIndexes: file_v1_chat_service_proto_depIdxs,
	}.Build()
	File_v1_chat_service_proto = out.File
	file_v1_chat_service_proto_goTypes = nil
	file_v1_chat_service_proto_depIdxs = nil
}
