// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: v1/auth_service.proto

package auth

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_v1_auth_service_proto protoreflect.FileDescriptor

const file_v1_auth_service_proto_rawDesc = "" +
	"\n" +
	"\x15v1/auth_service.proto\x12-github.com.DeNisBuLgAkOv.msa_big_tech.auth.v1\x1a\x16v1/auth_messages.proto\x1a\x1cgoogle/api/annotations.proto2\xfe\x03\n" +
	"\vAuthService\x12\xa8\x01\n" +
	"\bRegister\x12>.github.com.DeNisBuLgAkOv.msa_big_tech.auth.v1.RegisterRequest\x1a?.github.com.DeNisBuLgAkOv.msa_big_tech.auth.v1.RegisterResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/register\x12\x9c\x01\n" +
	"\x05Login\x12;.github.com.DeNisBuLgAkOv.msa_big_tech.auth.v1.LoginRequest\x1a<.github.com.DeNisBuLgAkOv.msa_big_tech.auth.v1.LoginResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/login\x12\xa4\x01\n" +
	"\aRefresh\x12=.github.com.DeNisBuLgAkOv.msa_big_tech.auth.v1.RefreshRequest\x1a>.github.com.DeNisBuLgAkOv.msa_big_tech.auth.v1.RefreshResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/v1/refreshB\xbc\x02\n" +
	"1com.github.com.DeNisBuLgAkOv.msa_big_tech.auth.v1B\x10AuthServiceProtoP\x01Z\"msa_big_tech/pkg/api/proto/v1;auth\xa2\x02\x05GCDMA\xaa\x02+Github.Com.DeNisBuLgAkOv.MsaBigTech.Auth.V1\xca\x02+Github\\Com\\DeNisBuLgAkOv\\MsaBigTech\\Auth\\V1\xe2\x027Github\\Com\\DeNisBuLgAkOv\\MsaBigTech\\Auth\\V1\\GPBMetadata\xea\x020Github::Com::DeNisBuLgAkOv::MsaBigTech::Auth::V1b\x06proto3"

var file_v1_auth_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: github.com.DeNisBuLgAkOv.msa_big_tech.auth.v1.RegisterRequest
	(*LoginRequest)(nil),     // 1: github.com.DeNisBuLgAkOv.msa_big_tech.auth.v1.LoginRequest
	(*RefreshRequest)(nil),   // 2: github.com.DeNisBuLgAkOv.msa_big_tech.auth.v1.RefreshRequest
	(*RegisterResponse)(nil), // 3: github.com.DeNisBuLgAkOv.msa_big_tech.auth.v1.RegisterResponse
	(*LoginResponse)(nil),    // 4: github.com.DeNisBuLgAkOv.msa_big_tech.auth.v1.LoginResponse
	(*RefreshResponse)(nil),  // 5: github.com.DeNisBuLgAkOv.msa_big_tech.auth.v1.RefreshResponse
}
var file_v1_auth_service_proto_depIdxs = []int32{
	0, // 0: github.com.DeNisBuLgAkOv.msa_big_tech.auth.v1.AuthService.Register:input_type -> github.com.DeNisBuLgAkOv.msa_big_tech.auth.v1.RegisterRequest
	1, // 1: github.com.DeNisBuLgAkOv.msa_big_tech.auth.v1.AuthService.Login:input_type -> github.com.DeNisBuLgAkOv.msa_big_tech.auth.v1.LoginRequest
	2, // 2: github.com.DeNisBuLgAkOv.msa_big_tech.auth.v1.AuthService.Refresh:input_type -> github.com.DeNisBuLgAkOv.msa_big_tech.auth.v1.RefreshRequest
	3, // 3: github.com.DeNisBuLgAkOv.msa_big_tech.auth.v1.AuthService.Register:output_type -> github.com.DeNisBuLgAkOv.msa_big_tech.auth.v1.RegisterResponse
	4, // 4: github.com.DeNisBuLgAkOv.msa_big_tech.auth.v1.AuthService.Login:output_type -> github.com.DeNisBuLgAkOv.msa_big_tech.auth.v1.LoginResponse
	5, // 5: github.com.DeNisBuLgAkOv.msa_big_tech.auth.v1.AuthService.Refresh:output_type -> github.com.DeNisBuLgAkOv.msa_big_tech.auth.v1.RefreshResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_auth_service_proto_init() }
func file_v1_auth_service_proto_init() {
	if File_v1_auth_service_proto != nil {
		return
	}
	file_v1_auth_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_auth_service_proto_rawDesc), len(file_v1_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_auth_service_proto_goTypes,
		DependencyIndexes: file_v1_auth_service_proto_depIdxs,
	}.Build()
	File_v1_auth_service_proto = out.File
	file_v1_auth_service_proto_goTypes = nil
	file_v1_auth_service_proto_depIdxs = nil
}
