// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/social_messages.proto

package social

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_PENDING  Status = 0
	Status_STATUS_APPROVED Status = 1
	Status_STATUS_DECLINED Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_PENDING",
		1: "STATUS_APPROVED",
		2: "STATUS_DECLINED",
	}
	Status_value = map[string]int32{
		"STATUS_PENDING":  0,
		"STATUS_APPROVED": 1,
		"STATUS_DECLINED": 2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_social_messages_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_v1_social_messages_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_v1_social_messages_proto_rawDescGZIP(), []int{0}
}

// Объекты
type FriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	FromUserId    string                 `protobuf:"bytes,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"` // Кто отправил заявку
	ToUserId      string                 `protobuf:"bytes,3,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`       // Кому отправили заявку
	Status        Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequest) Reset() {
	*x = FriendRequest{}
	mi := &file_v1_social_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequest) ProtoMessage() {}

func (x *FriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_social_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequest.ProtoReflect.Descriptor instead.
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return file_v1_social_messages_proto_rawDescGZIP(), []int{0}
}

func (x *FriendRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FriendRequest) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *FriendRequest) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *FriendRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_PENDING
}

// Отправить заявку
type SendFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToUserId      string                 `protobuf:"bytes,1,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"` // Кому отправляем заявку (from_user_id берется из авторизации)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestRequest) Reset() {
	*x = SendFriendRequestRequest{}
	mi := &file_v1_social_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestRequest) ProtoMessage() {}

func (x *SendFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_social_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*SendFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_v1_social_messages_proto_rawDescGZIP(), []int{1}
}

func (x *SendFriendRequestRequest) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

type SendFriendRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendRequest *FriendRequest         `protobuf:"bytes,1,opt,name=friend_request,json=friendRequest,proto3" json:"friend_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestResponse) Reset() {
	*x = SendFriendRequestResponse{}
	mi := &file_v1_social_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestResponse) ProtoMessage() {}

func (x *SendFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_social_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*SendFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_v1_social_messages_proto_rawDescGZIP(), []int{2}
}

func (x *SendFriendRequestResponse) GetFriendRequest() *FriendRequest {
	if x != nil {
		return x.FriendRequest
	}
	return nil
}

// Входящие заявки
type ListRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestsRequest) Reset() {
	*x = ListRequestsRequest{}
	mi := &file_v1_social_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsRequest) ProtoMessage() {}

func (x *ListRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_social_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListRequestsRequest) Descriptor() ([]byte, []int) {
	return file_v1_social_messages_proto_rawDescGZIP(), []int{3}
}

type ListRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*FriendRequest       `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestsResponse) Reset() {
	*x = ListRequestsResponse{}
	mi := &file_v1_social_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsResponse) ProtoMessage() {}

func (x *ListRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_social_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListRequestsResponse) Descriptor() ([]byte, []int) {
	return file_v1_social_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ListRequestsResponse) GetRequests() []*FriendRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

// Принять заявку
type AcceptFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendRequestRequest) Reset() {
	*x = AcceptFriendRequestRequest{}
	mi := &file_v1_social_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendRequestRequest) ProtoMessage() {}

func (x *AcceptFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_social_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*AcceptFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_v1_social_messages_proto_rawDescGZIP(), []int{5}
}

func (x *AcceptFriendRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type AcceptFriendRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendRequest *FriendRequest         `protobuf:"bytes,1,opt,name=friend_request,json=friendRequest,proto3" json:"friend_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendRequestResponse) Reset() {
	*x = AcceptFriendRequestResponse{}
	mi := &file_v1_social_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendRequestResponse) ProtoMessage() {}

func (x *AcceptFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_social_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*AcceptFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_v1_social_messages_proto_rawDescGZIP(), []int{6}
}

func (x *AcceptFriendRequestResponse) GetFriendRequest() *FriendRequest {
	if x != nil {
		return x.FriendRequest
	}
	return nil
}

// Отклонить заявку
type DeclineFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineFriendRequestRequest) Reset() {
	*x = DeclineFriendRequestRequest{}
	mi := &file_v1_social_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineFriendRequestRequest) ProtoMessage() {}

func (x *DeclineFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_social_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*DeclineFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_v1_social_messages_proto_rawDescGZIP(), []int{7}
}

func (x *DeclineFriendRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type DeclineFriendRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendRequest *FriendRequest         `protobuf:"bytes,1,opt,name=friend_request,json=friendRequest,proto3" json:"friend_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineFriendRequestResponse) Reset() {
	*x = DeclineFriendRequestResponse{}
	mi := &file_v1_social_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineFriendRequestResponse) ProtoMessage() {}

func (x *DeclineFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_social_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*DeclineFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_v1_social_messages_proto_rawDescGZIP(), []int{8}
}

func (x *DeclineFriendRequestResponse) GetFriendRequest() *FriendRequest {
	if x != nil {
		return x.FriendRequest
	}
	return nil
}

// Удалить пользователя из друзей
type RemoveFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendUserId  string                 `protobuf:"bytes,1,opt,name=friend_user_id,json=friendUserId,proto3" json:"friend_user_id,omitempty"` // Четкое название - кого удаляем из друзей
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFriendRequest) Reset() {
	*x = RemoveFriendRequest{}
	mi := &file_v1_social_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendRequest) ProtoMessage() {}

func (x *RemoveFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_social_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendRequest.ProtoReflect.Descriptor instead.
func (*RemoveFriendRequest) Descriptor() ([]byte, []int) {
	return file_v1_social_messages_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveFriendRequest) GetFriendUserId() string {
	if x != nil {
		return x.FriendUserId
	}
	return ""
}

type RemoveFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFriendResponse) Reset() {
	*x = RemoveFriendResponse{}
	mi := &file_v1_social_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendResponse) ProtoMessage() {}

func (x *RemoveFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_social_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendResponse.ProtoReflect.Descriptor instead.
func (*RemoveFriendResponse) Descriptor() ([]byte, []int) {
	return file_v1_social_messages_proto_rawDescGZIP(), []int{10}
}

// Список друзей
type ListFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"` // user_id берется из авторизации (чьих друзей показываем)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsRequest) Reset() {
	*x = ListFriendsRequest{}
	mi := &file_v1_social_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsRequest) ProtoMessage() {}

func (x *ListFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_social_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsRequest.ProtoReflect.Descriptor instead.
func (*ListFriendsRequest) Descriptor() ([]byte, []int) {
	return file_v1_social_messages_proto_rawDescGZIP(), []int{11}
}

func (x *ListFriendsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListFriendsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListFriendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendUserIds []string               `protobuf:"bytes,1,rep,name=friend_user_ids,json=friendUserIds,proto3" json:"friend_user_ids,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsResponse) Reset() {
	*x = ListFriendsResponse{}
	mi := &file_v1_social_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsResponse) ProtoMessage() {}

func (x *ListFriendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_social_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsResponse.ProtoReflect.Descriptor instead.
func (*ListFriendsResponse) Descriptor() ([]byte, []int) {
	return file_v1_social_messages_proto_rawDescGZIP(), []int{12}
}

func (x *ListFriendsResponse) GetFriendUserIds() []string {
	if x != nil {
		return x.FriendUserIds
	}
	return nil
}

func (x *ListFriendsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

var File_v1_social_messages_proto protoreflect.FileDescriptor

const file_v1_social_messages_proto_rawDesc = "" +
	"\n" +
	"\x18v1/social_messages.proto\x12/github.com.DeNisBuLgAkOv.msa_big_tech.social.v1\"\xbf\x01\n" +
	"\rFriendRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\tR\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x03 \x01(\tR\btoUserId\x12O\n" +
	"\x06status\x18\x04 \x01(\x0e27.github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.StatusR\x06status\"8\n" +
	"\x18SendFriendRequestRequest\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x01 \x01(\tR\btoUserId\"\x82\x01\n" +
	"\x19SendFriendRequestResponse\x12e\n" +
	"\x0efriend_request\x18\x01 \x01(\v2>.github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.FriendRequestR\rfriendRequest\"\x15\n" +
	"\x13ListRequestsRequest\"r\n" +
	"\x14ListRequestsResponse\x12Z\n" +
	"\brequests\x18\x01 \x03(\v2>.github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.FriendRequestR\brequests\";\n" +
	"\x1aAcceptFriendRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\x84\x01\n" +
	"\x1bAcceptFriendRequestResponse\x12e\n" +
	"\x0efriend_request\x18\x01 \x01(\v2>.github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.FriendRequestR\rfriendRequest\"<\n" +
	"\x1bDeclineFriendRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\x85\x01\n" +
	"\x1cDeclineFriendRequestResponse\x12e\n" +
	"\x0efriend_request\x18\x01 \x01(\v2>.github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.FriendRequestR\rfriendRequest\";\n" +
	"\x13RemoveFriendRequest\x12$\n" +
	"\x0efriend_user_id\x18\x01 \x01(\tR\ffriendUserId\"\x16\n" +
	"\x14RemoveFriendResponse\"B\n" +
	"\x12ListFriendsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\"^\n" +
	"\x13ListFriendsResponse\x12&\n" +
	"\x0ffriend_user_ids\x18\x01 \x03(\tR\rfriendUserIds\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor*F\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x00\x12\x13\n" +
	"\x0fSTATUS_APPROVED\x10\x01\x12\x13\n" +
	"\x0fSTATUS_DECLINED\x10\x02B\xcb\x02\n" +
	"3com.github.com.DeNisBuLgAkOv.msa_big_tech.social.v1B\x13SocialMessagesProtoP\x01Z$msa_big_tech/pkg/api/proto/v1;social\xa2\x02\x05GCDMS\xaa\x02-Github.Com.DeNisBuLgAkOv.MsaBigTech.Social.V1\xca\x02-Github\\Com\\DeNisBuLgAkOv\\MsaBigTech\\Social\\V1\xe2\x029Github\\Com\\DeNisBuLgAkOv\\MsaBigTech\\Social\\V1\\GPBMetadata\xea\x022Github::Com::DeNisBuLgAkOv::MsaBigTech::Social::V1b\x06proto3"

var (
	file_v1_social_messages_proto_rawDescOnce sync.Once
	file_v1_social_messages_proto_rawDescData []byte
)

func file_v1_social_messages_proto_rawDescGZIP() []byte {
	file_v1_social_messages_proto_rawDescOnce.Do(func() {
		file_v1_social_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_social_messages_proto_rawDesc), len(file_v1_social_messages_proto_rawDesc)))
	})
	return file_v1_social_messages_proto_rawDescData
}

var file_v1_social_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_social_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_v1_social_messages_proto_goTypes = []any{
	(Status)(0),                          // 0: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.Status
	(*FriendRequest)(nil),                // 1: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.FriendRequest
	(*SendFriendRequestRequest)(nil),     // 2: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.SendFriendRequestRequest
	(*SendFriendRequestResponse)(nil),    // 3: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.SendFriendRequestResponse
	(*ListRequestsRequest)(nil),          // 4: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.ListRequestsRequest
	(*ListRequestsResponse)(nil),         // 5: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.ListRequestsResponse
	(*AcceptFriendRequestRequest)(nil),   // 6: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.AcceptFriendRequestRequest
	(*AcceptFriendRequestResponse)(nil),  // 7: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.AcceptFriendRequestResponse
	(*DeclineFriendRequestRequest)(nil),  // 8: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.DeclineFriendRequestRequest
	(*DeclineFriendRequestResponse)(nil), // 9: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.DeclineFriendRequestResponse
	(*RemoveFriendRequest)(nil),          // 10: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.RemoveFriendRequest
	(*RemoveFriendResponse)(nil),         // 11: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.RemoveFriendResponse
	(*ListFriendsRequest)(nil),           // 12: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.ListFriendsRequest
	(*ListFriendsResponse)(nil),          // 13: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.ListFriendsResponse
}
var file_v1_social_messages_proto_depIdxs = []int32{
	0, // 0: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.FriendRequest.status:type_name -> github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.Status
	1, // 1: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.SendFriendRequestResponse.friend_request:type_name -> github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.FriendRequest
	1, // 2: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.ListRequestsResponse.requests:type_name -> github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.FriendRequest
	1, // 3: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.AcceptFriendRequestResponse.friend_request:type_name -> github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.FriendRequest
	1, // 4: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.DeclineFriendRequestResponse.friend_request:type_name -> github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.FriendRequest
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_v1_social_messages_proto_init() }
func file_v1_social_messages_proto_init() {
	if File_v1_social_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_social_messages_proto_rawDesc), len(file_v1_social_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_social_messages_proto_goTypes,
		DependencyIndexes: file_v1_social_messages_proto_depIdxs,
		EnumInfos:         file_v1_social_messages_proto_enumTypes,
		MessageInfos:      file_v1_social_messages_proto_msgTypes,
	}.Build()
	File_v1_social_messages_proto = out.File
	file_v1_social_messages_proto_goTypes = nil
	file_v1_social_messages_proto_depIdxs = nil
}
