// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/social_service.proto

package social

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_v1_social_service_proto protoreflect.FileDescriptor

const file_v1_social_service_proto_rawDesc = "" +
	"\n" +
	"\x17v1/social_service.proto\x12/github.com.DeNisBuLgAkOv.msa_big_tech.social.v1\x1a\x18v1/social_messages.proto\x1a\x1cgoogle/api/annotations.proto2\xa7\b\n" +
	"\rSocialService\x12\xcb\x01\n" +
	"\x11SendFriendRequest\x12I.github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.SendFriendRequestRequest\x1aJ.github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.SendFriendRequestResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\"\x17/api/v1/friends/request\x12\x9d\x01\n" +
	"\fListRequests\x12D.github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.ListRequestsRequest\x1aE.github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.ListRequestsResponse\"\x00\x12\xb2\x01\n" +
	"\x13AcceptFriendRequest\x12K.github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.AcceptFriendRequestRequest\x1aL.github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.AcceptFriendRequestResponse\"\x00\x12\xb5\x01\n" +
	"\x14DeclineFriendRequest\x12L.github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.DeclineFriendRequestRequest\x1aM.github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.DeclineFriendRequestResponse\"\x00\x12\x9d\x01\n" +
	"\fRemoveFriend\x12D.github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.RemoveFriendRequest\x1aE.github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.RemoveFriendResponse\"\x00\x12\x9a\x01\n" +
	"\vListFriends\x12C.github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.ListFriendsRequest\x1aD.github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.ListFriendsResponse\"\x00B\xca\x02\n" +
	"3com.github.com.DeNisBuLgAkOv.msa_big_tech.social.v1B\x12SocialServiceProtoP\x01Z$msa_big_tech/pkg/api/proto/v1;social\xa2\x02\x05GCDMS\xaa\x02-Github.Com.DeNisBuLgAkOv.MsaBigTech.Social.V1\xca\x02-Github\\Com\\DeNisBuLgAkOv\\MsaBigTech\\Social\\V1\xe2\x029Github\\Com\\DeNisBuLgAkOv\\MsaBigTech\\Social\\V1\\GPBMetadata\xea\x022Github::Com::DeNisBuLgAkOv::MsaBigTech::Social::V1b\x06proto3"

var file_v1_social_service_proto_goTypes = []any{
	(*SendFriendRequestRequest)(nil),     // 0: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.SendFriendRequestRequest
	(*ListRequestsRequest)(nil),          // 1: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.ListRequestsRequest
	(*AcceptFriendRequestRequest)(nil),   // 2: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.AcceptFriendRequestRequest
	(*DeclineFriendRequestRequest)(nil),  // 3: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.DeclineFriendRequestRequest
	(*RemoveFriendRequest)(nil),          // 4: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.RemoveFriendRequest
	(*ListFriendsRequest)(nil),           // 5: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.ListFriendsRequest
	(*SendFriendRequestResponse)(nil),    // 6: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.SendFriendRequestResponse
	(*ListRequestsResponse)(nil),         // 7: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.ListRequestsResponse
	(*AcceptFriendRequestResponse)(nil),  // 8: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.AcceptFriendRequestResponse
	(*DeclineFriendRequestResponse)(nil), // 9: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.DeclineFriendRequestResponse
	(*RemoveFriendResponse)(nil),         // 10: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.RemoveFriendResponse
	(*ListFriendsResponse)(nil),          // 11: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.ListFriendsResponse
}
var file_v1_social_service_proto_depIdxs = []int32{
	0,  // 0: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.SocialService.SendFriendRequest:input_type -> github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.SendFriendRequestRequest
	1,  // 1: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.SocialService.ListRequests:input_type -> github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.ListRequestsRequest
	2,  // 2: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.SocialService.AcceptFriendRequest:input_type -> github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.AcceptFriendRequestRequest
	3,  // 3: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.SocialService.DeclineFriendRequest:input_type -> github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.DeclineFriendRequestRequest
	4,  // 4: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.SocialService.RemoveFriend:input_type -> github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.RemoveFriendRequest
	5,  // 5: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.SocialService.ListFriends:input_type -> github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.ListFriendsRequest
	6,  // 6: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.SocialService.SendFriendRequest:output_type -> github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.SendFriendRequestResponse
	7,  // 7: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.SocialService.ListRequests:output_type -> github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.ListRequestsResponse
	8,  // 8: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.SocialService.AcceptFriendRequest:output_type -> github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.AcceptFriendRequestResponse
	9,  // 9: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.SocialService.DeclineFriendRequest:output_type -> github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.DeclineFriendRequestResponse
	10, // 10: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.SocialService.RemoveFriend:output_type -> github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.RemoveFriendResponse
	11, // 11: github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.SocialService.ListFriends:output_type -> github.com.DeNisBuLgAkOv.msa_big_tech.social.v1.ListFriendsResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_v1_social_service_proto_init() }
func file_v1_social_service_proto_init() {
	if File_v1_social_service_proto != nil {
		return
	}
	file_v1_social_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_social_service_proto_rawDesc), len(file_v1_social_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_social_service_proto_goTypes,
		DependencyIndexes: file_v1_social_service_proto_depIdxs,
	}.Build()
	File_v1_social_service_proto = out.File
	file_v1_social_service_proto_goTypes = nil
	file_v1_social_service_proto_depIdxs = nil
}
