// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/users_service.proto

package users

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_v1_users_service_proto protoreflect.FileDescriptor

const file_v1_users_service_proto_rawDesc = "" +
	"\n" +
	"\x16v1/users_service.proto\x12.github.com.DeNisBuLgAkOv.msa_big_tech.users.v1\x1a\x17v1/users_messages.proto\x1a\x1cgoogle/api/annotations.proto2\x84\a\n" +
	"\fUsersService\x12\x9e\x01\n" +
	"\rCreateProfile\x12D.github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.CreateProfileRequest\x1aE.github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.CreateProfileResponse\"\x00\x12\x9e\x01\n" +
	"\rUpdateProfile\x12D.github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.UpdateProfileRequest\x1aE.github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.UpdateProfileResponse\"\x00\x12\xb9\x01\n" +
	"\x0eGetProfileByID\x12E.github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.GetProfileByIDRequest\x1aF.github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.GetProfileByIDResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/profile/{id}\x12\xb3\x01\n" +
	"\x14GetProfileByNickname\x12K.github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.GetProfileByNicknameRequest\x1aL.github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.GetProfileByNicknameResponse\"\x00\x12\xbf\x01\n" +
	"\x10SearchByNickname\x12G.github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.SearchByNicknameRequest\x1aH.github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.SearchByNicknameResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/users/searchB\xc3\x02\n" +
	"2com.github.com.DeNisBuLgAkOv.msa_big_tech.users.v1B\x11UsersServiceProtoP\x01Z#msa_big_tech/pkg/api/proto/v1;users\xa2\x02\x05GCDMU\xaa\x02,Github.Com.DeNisBuLgAkOv.MsaBigTech.Users.V1\xca\x02,Github\\Com\\DeNisBuLgAkOv\\MsaBigTech\\Users\\V1\xe2\x028Github\\Com\\DeNisBuLgAkOv\\MsaBigTech\\Users\\V1\\GPBMetadata\xea\x021Github::Com::DeNisBuLgAkOv::MsaBigTech::Users::V1b\x06proto3"

var file_v1_users_service_proto_goTypes = []any{
	(*CreateProfileRequest)(nil),         // 0: github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.CreateProfileRequest
	(*UpdateProfileRequest)(nil),         // 1: github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.UpdateProfileRequest
	(*GetProfileByIDRequest)(nil),        // 2: github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.GetProfileByIDRequest
	(*GetProfileByNicknameRequest)(nil),  // 3: github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.GetProfileByNicknameRequest
	(*SearchByNicknameRequest)(nil),      // 4: github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.SearchByNicknameRequest
	(*CreateProfileResponse)(nil),        // 5: github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.CreateProfileResponse
	(*UpdateProfileResponse)(nil),        // 6: github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.UpdateProfileResponse
	(*GetProfileByIDResponse)(nil),       // 7: github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.GetProfileByIDResponse
	(*GetProfileByNicknameResponse)(nil), // 8: github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.GetProfileByNicknameResponse
	(*SearchByNicknameResponse)(nil),     // 9: github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.SearchByNicknameResponse
}
var file_v1_users_service_proto_depIdxs = []int32{
	0, // 0: github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.UsersService.CreateProfile:input_type -> github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.CreateProfileRequest
	1, // 1: github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.UsersService.UpdateProfile:input_type -> github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.UpdateProfileRequest
	2, // 2: github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.UsersService.GetProfileByID:input_type -> github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.GetProfileByIDRequest
	3, // 3: github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.UsersService.GetProfileByNickname:input_type -> github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.GetProfileByNicknameRequest
	4, // 4: github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.UsersService.SearchByNickname:input_type -> github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.SearchByNicknameRequest
	5, // 5: github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.UsersService.CreateProfile:output_type -> github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.CreateProfileResponse
	6, // 6: github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.UsersService.UpdateProfile:output_type -> github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.UpdateProfileResponse
	7, // 7: github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.UsersService.GetProfileByID:output_type -> github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.GetProfileByIDResponse
	8, // 8: github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.UsersService.GetProfileByNickname:output_type -> github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.GetProfileByNicknameResponse
	9, // 9: github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.UsersService.SearchByNickname:output_type -> github.com.DeNisBuLgAkOv.msa_big_tech.users.v1.SearchByNicknameResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_users_service_proto_init() }
func file_v1_users_service_proto_init() {
	if File_v1_users_service_proto != nil {
		return
	}
	file_v1_users_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_users_service_proto_rawDesc), len(file_v1_users_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_users_service_proto_goTypes,
		DependencyIndexes: file_v1_users_service_proto_depIdxs,
	}.Build()
	File_v1_users_service_proto = out.File
	file_v1_users_service_proto_goTypes = nil
	file_v1_users_service_proto_depIdxs = nil
}
